name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14' # The Go version to download (if necessary) and use.
    - name: Build and run tests
      run: |
        echo Running all the tests
        go test ./...
    - name: Publish to docker Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ayache/apigw-publisher
